### ISSUE TITLE
Some opcodes not handled correctly

### ISSUE THREAD

**Issue by arcusmaximus** [TesterTesterov/AI6WINScriptTool#2]
Found some opcodes that appear to be handled incorrectly.

The most important one is opcode 1A, which registers a choice. It has an int32 operand and is followed by a 0A message instruction, and the operand is an address used to jump over the message. However, AI6WINScriptTool doesn't interpret the operand as an address and doesn't adjust it when assembling, which means scripts containing choices get broken if you change something.

As an example, disassemble sis4_asah1_eriko.mes from AiShimai IV (same game as mentioned in #1), change the text of some message, reassemble, and try the scenario ingame (just hold Ctrl for a bit until you hit the choice screen). It'll result in an error messagebox.

Others:
- Opcode 10 is disassembled with a byte operand, but in AiShimai, it doesn't have any operands. (It's a store operation that simply pops a target index and a value)
- Similarly, opcode 36 doesn't have any operands in AiShimai. (Pops two values, multiplies them and pushes the result)
- The operand of opcode 32 is one big-endian int32, not two int16s.

Finally, I found the following opcode meanings. Might be useful to make the disassembly more readable:
```
00              // pause, yield...? - interrupts scenario execution
01              // ret - return from library function (appears to have no operands)
02              // ldglob1.i8 - pops an index and pushes the corresponding byte
03              // ldglob2.i16
04              // ldglob3.var - for variants (which may contain an int or a string)
05              // ldglob4.var - as above, but from a different list
06              // ldloc.var
07              // ldglob5.i8 - these three all access the same list
08              // ldglob5.i16
09              // ldglob5.i32

0C              // stglob1.i8 - pops an index and a value, then stores the value to the byte at the index
0D              // stglob2.i16
0E              // stglob3.var
0F              // stglob4.var
10              // stloc.var
11              // stglob5.i8
12              // stglob5.i16
13              // stglob5.i32

14 i32          // jz - pops a value and jumps to the address if it's 0
15 i32          // jmp (unconditional)
16 i32          // libreg - pops ID and number of arguments and registers a "liblary" function
17              // libcall - pops ID and arguments and calls a "liblary" function
18              // syscall - pops ID and arguments and calls builtin function (related to sprites, voices etc)
1A i32          // choice - remembers the address of the next instruction and jumps to the operand address
1B i8           // escape sequence. AI6WIN only has 00 = line break.
                // Silky's also has 01 = begin ruby sequence (ended by opcode 00)

32 i32          // push.i32
33 sz           // push.s
34              // add - pops A and B, then pushes A + B; also works for strings
35              // sub
36              // mul
37              // div
38              // mod
39              // rand - pops a seed and pushes a random value
3A              // logand - pops A and B, then pushes 1 if they're both 1, or 0 otherwise
3B              // logor - pops A and B, then pushes 1 if either of them is 1
3C              // binand
3D              // binor
3E              // lt - pops A and B, then pushes 1 if B < A
3F              // gt
40              // le
41              // ge
42              // eq
43              // neq
```

**Comment by TesterTesterov** [comment]
Indeed. I made the tool quite in haste, therefore I made some mistakes...

I'd update the tool accordingly, as I'll have time. I'd need to add the version system, since AiShimai's version has a slight differences.

**Comment by TesterTesterov** [comment]
@arcusmaximus, done. See [version 2.0](https://github.com/TesterTesterov/AI6WINScriptTool/releases/tag/2.0).
